name: Veracode Static Policy Scanner

on:
  workflow_call:
    inputs:
      profile_name:
        required: false
        type: string
      policy_name:
        required: true
        type: string
      modules_to_scan:
        required: true
        type: string
      owner:
        required: true
        type: string
      repo:
        required: true
        type: string
      sha:
        required: true
        type: string
      token:
        required: true
        type: string
      ref:
        required: true
        type: string
      security_report_enabled:
        required: true
        type: boolean
      create_issue:
        required: true
        type: boolean
      source_repository:
          required: true
          type: string 
      check_run_id:
          required: true
          type: string      


jobs:
  policy_scan:
    runs-on: ubuntu-latest
    name: policy scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      # get the compiled binary from a previous job
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: veracode-artifact
          path: ./veracode_artifact_directory
      
      - name: Get the name of the downloaded files
        run: |
          artifact_file=$(ls -1 ./veracode_artifact_directory | head -n 1)
          echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV
      # run the policy scan action
      - name: Veracode Upload and Scan Action Step
        uses: veracode/uploadandscan-action@main
        id: upload_and_scan
        with:
          appname: ${{ inputs.source_repository }}
          createprofile: true
          policy: ${{ inputs.policy_name }}
          version: '${{ github.run_id }}'
          filepath: ./veracode_artifact_directory/${{ env.veracode_artifact }}
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          #scanpollinginterval: 30
          scantimeout: 55
          include: ${{ inputs.modules_to_scan }}
          failbuild: true

      - name: Veracode Policy Results
        if: always() 
        uses: veracode/workflow-app-helper@main
        with:
          action: preparePolicyResults
          token: ${{ inputs.token }}
          check_run_id: ${{ inputs.check_run_id }}
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          appname: ${{ inputs.source_repository }} 
          source_repository: ${{ inputs.source_repository }} 
  
 
