name: Veracode Static Code Analysis

run-name: Static Code Analysis - ${{ github.event.client_payload.repository.name }}

on:
  repository_dispatch:
    types: [java-maven-pipeline-scan,
            java-maven-policy-scan,
            java-maven-sandbox-scan,
            java-gradle-pipeline-scan,
            java-gradle-policy-scan,
            java-gradle-sandbox-scan,
            source-code-pipeline-scan,
            source-code-policy-scan,
            source-code-sandbox-scan,
            dot-net-pipeline-scan,
            dot-net-policy-scan,
            dot-net-sandbox-scan,
            go-pipeline-scan,
            go-policy-scan,
            go-sandbox-scan,
            tsql-pipeline-scan,
            tsql-policy-scan,
            tsql-sandbox-scan,
            plsql-pipeline-scan,
            plsql-policy-scan,
            plsql-sandbox-scan,
            php-pipeline-scan,
            php-policy-scan,
            php-sandbox-scan,
            scala-pipeline-scan,
            scala-policy-scan,
            scala-sandbox-scan,
            dart-pipeline-scan,
            dart-policy-scan,
            dart-sandbox-scan]

jobs:
  register:
    uses: ./.github/workflows/veracode-check-run.yml
    with:
      check_run_name: ${{ github.workflow }}
      head_sha: ${{ github.event.client_payload.sha }}
      repositroy_owner: ${{ github.event.client_payload.repository.owner }}
      repositroy_name: ${{ github.event.client_payload.repository.name }}
      event_type: ${{ github.event.client_payload.event_type }}
      github_token: ${{ github.event.client_payload.token }}
      run_id: ${{ github.run_id }}
        
  build:
    needs: register
    uses: ./.github/workflows/veracode-build-artifact-for-scanning.yml
    with:
      repository: ${{ github.event.client_payload.repository.full_name }}
      ref: ${{ github.event.client_payload.sha }}
      token: ${{ github.event.client_payload.token }}
      event_name: ${{ github.event.action }}


  pipeline_scan:
    # needs the build step before this job will start running
    needs: build
    if: contains(github.event.action, 'pipeline')
    uses: ./.github/workflows/veracode-pipeline-scan.yml
    with:
      policy_name: ${{ github.event.client_payload.policy_name }}
      enable_security_report: ${{ github.event.client_payload.enable_security_report }}
      owner: ${{ github.event.client_payload.repository.owner }}
      repo: ${{ github.event.client_payload.repository.name }}
      sha: ${{ github.event.client_payload.sha }}
      token: ${{ github.event.client_payload.token }}
      ref: ${{ github.event.client_payload.ref }}
    secrets: inherit
    
  policy_scan:
    needs: build
    if: contains(github.event.action, 'policy')
    uses: ./.github/workflows/veracode-policy-scan.yml
    with:
      profile_name: ${{ github.event.client_payload.profile_name }}
      policy_name: ${{ github.event.client_payload.policy_name }}
      modules_to_scan: ${{ github.event.client_payload.modules_to_scan }}
    secrets: inherit

  sandbox_scan:
    needs: build
    if: contains(github.event.action, 'policy')
    uses: ./.github/workflows/veracode-sandbox-scan.yml
    with:
      profile_name: ${{ github.event.client_payload.profile_name }}
      policy_name: ${{ github.event.client_payload.policy_name }}
      modules_to_scan: ${{ github.event.client_payload.modules_to_scan }}
    secrets: inherit
