name: Veracode Static Policy Scanner

on:
  workflow_call:
    inputs:
      profile_name:
        required: true
        type: string
      policy_name:
        required: true
        type: string
      modules_to_scan:
        required: true
        type: string
  
jobs:
  policy_scan:
    runs-on: ubuntu-latest
    name: policy scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      # get the compiled binary from a previous job
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: veracode-artifact
          path: ./veracode_artifact_directory
      
      - name: Get the name of the downloaded files
        run: |
          artifact_file=$(ls -1 ./veracode_artifact_directory | head -n 1)
          echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV
      # run the policy scan action
      - name: Veracode Upload and Scan Action Step
        uses: veracode/uploadandscan-action@main
        id: upload_and_scan
        with:
          appname: ${{ inputs.profile_name }}
          createprofile: true
          policy: ${{ inputs.policy_name }}
          version: '${{ github.run_id }}'
          filepath: ./veracode_artifact_directory/${{ env.veracode_artifact }}
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          #scanpollinginterval: 30
          scantimeout: 15
          include: ${{ inputs.modules_to_scan }}
          failbuild: true
# This step will import the flaws from the step above
  import-issues:
    needs: policy_scan

    if: ${{ inputs.create_issue && failure()}}
    runs-on: ubuntu-latest
    steps:
      - name: Get flaw file
        uses: actions/download-artifact@v3
        with:
          name: 'policy-flaws'
          path: /tmp
      - name: Import flaws as issues
        uses: veracode/veracode-flaws-to-issues@addWorkflowAppSupport
        with:
          scan-results-json: '/tmp/policy_flaws.json'
          repo_owner: ${{ github.event.client_payload.repository.owner }}
          repo_name: ${{ github.event.client_payload.repository.name }}
          github-token: ${{ github.event.client_payload.token }}
        
